### PR TITLE
Add IE/Edge compatibility to line graph

### LINKED ISSUE #43: Fix scrubber and mouse alignment in Edge & IE11
ieoffset

The scrubber is left offset from the mouse positioning on Edge and IE11.

This is an issue when using Temperate or Lab.

### PR DESCRIPTION
**Pull request by fungjj92**
## Overview

The line graph scrubber was offset in IE and Edge, but we need to account for those browser users.

Line 273 is the code block that changed functionally.
The rest is just spacing clean up that was driving me nuts.

## Testing Instructions

I had made [a plunkr of the line graph](https://plnkr.co/edit/9xmWDeHHuo2pwl0tVyKf) with some basic and dummy data that I used to test this change. Try it out in different browsers to see it scrubs correctly with regard to cursor position. Note, the scrubber doesn't follow the line, but rather data points broken at their midpoints. 

## Checklist
- [x] `yarn run lint` clean?
- [x] `yarn run build:library` clean?
- [x] `npm pack` clean?
- [x] `CHANGELOG.md` updated?

Closes #43

### CODE REVIEW

**Comment by maurizi** [comment]
I tried to test this out in my Temperate dev environment, but I ran into weird Angular issues and wasn't able to. I'll give it another shot tomorrow.

**Comment by rmartz** [comment]
I'm running into trouble testing this - whenever I load it up in the lab on browserstack I still see the scrubber being offset. Getting it configured in Temperate wasn't making headway but the lab at least appears to be more forthcoming. I have it built in `climate-change-components-0.2.14.tgz` and my lab `package.json` appears to reference it correctly:
```
    "climate-change-components": "file:../climate-change-components/climate-change-components-0.2.14.tgz",
```
Yarn installs and runs fine, but when I load it up it's still offset. Maybe we might need to pair to see if we can figure what's up?

**Comment by fungjj92** [comment]
This is updated :o)

**Review by rmartz — APPROVED** [review]
LGTM!

**Pull request merged**
